openapi: 3.0.1
info:
  title: RestRserve OpenAPI
  version: '1.0'
servers:
  - url: /

tags:
  - name: version
    description: Information about R packages
  - name: data
    description: Retrieve example datasets or upload own dataset
  - name: imputation
    description: Impute missing data
  - name: fit
    description: Some predifined fits (optional)

paths:
  /version:
    get:
      tags:
        - version
      description: Software version
      responses:
        200:
          description: API response
          content:
            text/json:
              schema:
                type: string
                example: {"mice":["3.14.0"]}
        
  /exampledata:
    get:
      tags:
        - data
      description: Retrieve exmple datasets (nhanes, nhanes2)
      parameters:
        - name: "name"
          description: "Example Dataset name (nhanes or nhanes2), or full path of the csv file"
          in: query
          schema:
            type: string
          example: "nhanes"
          required: true
      responses:
        200:
          description: API response
          content:
            text/json:
              schema:
                type: string
                example: {"age":[1,2,1],"bmi":[null,22.7,null],"hyp":[null,1,1],"chl":[null,187,187]}
        400:
          description: Bad Request, not a valid example dataset.

  /data:
    post:
      tags:
        - data
      summary: Uploads a csv - file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csvfile:
                  type: string
                  format: binary

      responses:
        200:
          description: API response
          content:
            text/plain:
              schema:
              type: string
  /long:
    get:
      tags:
        - imputation
      description: Run mice imputation on a datasets (nhanes, nhanes2) or an own csv file.
      parameters:
        - name: "payload"
          description: "Json with keys \"data\", \"maxit\", \"m\", \"seed\"" 
          in: query
          schema:
            type: string
          example: "{\"data\":\"nhanes\",\"maxit\":2,\"m\":2,\"seed\":1}"
          required: true
      responses:
        200:
          description: API response
          content:
            text/json:
              schema:
                type: string
                example: "{\"age\":{\"1\":[],\"2\":[]},\"bmi\":{\"1\":[30.1,33.2,27.4],\"2\":[30.1,27.2,21.7]},\"hyp\":{\"1\":[1,2,1],\"2\":[1,2,2]},\"chl\":{\"1\":[187,218,238],\"2\":[187,218,187]}}"
        400:
          description: Bad Request.
  /fit:
    get:
      tags:
        - fit
      description: Fit a model.
      parameters:
        - name: "payload"
          description: "data: JSON of mice::complete output, model: lm, formula chl ~ age + bmi"
          in: query
          schema:
            type: string
          example: "{\"data\": [{\".imp\":1,\".id\":1,\"age\":1,\"bmi\":30.1,\"hyp\":1,\"chl\":187}], \"model\":[\"lm\"], \"formula\":[\"chl ~ age + bmi\"]}"
          required: true
      responses:
        200:
          description: API response
          content:
            text/json:
              schema:
                type: string
                example: "{\"coefficients\":[-16.8639,43.8989,5.0529],\"residuals\":[7.8716,1.3645, ...]}"
        400:
          description: Bad Request.
